GET http://localhost:5001/posts

###

@username = michael
@password = abc123

POST http://localhost:5001/register
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

###

# @name login
POST http://localhost:5001/login
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

###

# @name createPost
POST http://localhost:5001/posts
Content-type: application/json
Authorization: Bearer {{login.response.body.$.access_token}}

{
    "title": "A car",
    "content": "A car for sale!"
}

###

@postId = {{createPost.response.body.$.id}}

DELETE http://localhost:5001/posts/{{postId}}
Authorization: Bearer {{login.response.body.$.access_token}}

###

GET http://localhost:5001/users

###

DELETE http://localhost:5001/users/{{username}}
Authorization: Bearer {{login.response.body.$.access_token}}
